updated UI to work better for mobiles
CSYClubIIITK/eco-crypt pull request #30
Opened 2024-01-12 11:05 UTC by JamieCWW

Tweaked the bootstrap coding to have the buttons and nav sit better on mobile view

2024-01-12 12:44 UTC, sarthakg043 requested changes
I see no changes in the code and the problem persists

2024-01-12 12:47 UTC, JamieCWW commented
> I see no changes in the code and the problem persists

Sorry, realised i create PR from main not sub branch i created

2024-01-15 09:34 UTC, JamieCWW commented
Did you manage to get it to merge with my changes?

2024-01-17 12:48 UTC, sarthakg043 commented
@JamieCWW Are you going to commit changes?

2024-01-18 10:35 UTC, JamieCWW commented
> @JamieCWW Are you going to commit changes?

I have merged everything back into my main branch..

2024-01-18 13:31 UTC, sarthakg043 commented
@JamieCWW the changes aren't visible still

2024-01-18 14:52 UTC, JamieCWW commented
can you check this one please..https://github.com/CSYClubIIITK/eco-crypt/pull/31

2025-01-12 21:28 UTC, closed without merging